---
name: Run pokeapi-csv
on:
  - push
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Run pokeapi-csv
        run: uv run pokeapi-csv --path dump

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: pokeapi-csv-${{ github.sha }}
          path: dump
